- name: Creating Jenkins jobs
  hosts: localhost
  connection: local
  vars:
    jobs:
      - roboshop-terraform
      - frontend
      - catalogue
      - user
      - cart
      - shipping
      - payment
  roles:
    - jenkins-jobs