- name: Set up a template file
  ansible.builtin.template:
    src: mbp_pipeline.xml
    dest: /tmp/mbp_pipeline.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/mbp_pipeline.xml') }}"
    name: "{{ item }}"
    password: admin123
    url: http://172.31.84.117:8080
    user: admin